name: saturn
channels:
    - pytorch
    - fastai
    - rapidsai
    - nodefaults
    - conda-forge
dependencies:
    - cudatoolkit=11.3
    - cudatoolkit-dev=11.3
    - ipykernel=6.13.0
    - ipywidgets<9,>=8
    - pytorch=1.12.0
    - pip
    - python=3.9
    - pip:
      - transformers
      - aiohttp
      - fastapi
      - uvicorn
      - beautifulsoup4
      - torch<1.13,>=1.12.0
      - numpy<1.23,>=1.18
      - gptq


# TODO: Figure out the deal with the mkl lib
# Had to symlink all libmkl_*.so to libmkl_*.so.1
# .2 symlinks existed, but failed on fetching the .1s
