name: saturn
channels:
    - pytorch
    - fastai
    - rapidsai
    - nodefaults
    - conda-forge
dependencies:
    - cudatoolkit=11.7
    - cudatoolkit-dev=11.7
    - ipykernel=6.13.0
    - ipywidgets<9,>=8
    - pytorch>=1.13.0,<1.14.0
    - faiss-gpu
    - pip
    - python=3.9
    - pip:
      - streamlit
      - beautifulsoup4
      - scrapy
      - transformers
      - datasets
      - einops
      - sentencepiece
      - sentence_transformers
      - langchain
      - bitsandbytes
      - numpy<1.25,>=1.24
      - accelerate
      - xformers
      - mkl==2021.4.0
      - gptq
